[package]
name = "significance"
version = "0.1.0"
edition = "2021"

[lib]
name = "significance"
path = "src/lib.rs"

[[bin]]
name = "significance"
path = "src/bin/Significance.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[dev-dependencies]